remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Simon León Krug
description: Postdoc in golden-rule instanton theory at ETH Zürich
logo: profile_mod_SLK.png
show_downloads: False
